### ISSUE TITLE
If Object+ is going to be available separately to NestedTypes...

### ISSUE THREAD

**Issue by far-blue** [Volicon/objectplus#1]
... Then a huge :+1:  from me! I'd really like to be able to use Object+ in web components that have no other need to bring in the rest of NestedTypes :)

**Comment by gaperton** [comment]
Finally you got it. Enjoy. :)

All the features of original Object+, plus a bit more. Events, and mixins.

**Comment by far-blue** [comment]
yay, cool. Once again you have timed your release to just when we are busy preparing to release work ourselves so we can't jump on Object+ immediately but it will be something to play with over christmas :)
